
const animes2 = [
    {"Id":"17","Image":"https://cdn.noitatnemucod.net/thumbnail/300x400/100/65f92e6e315a931ef872da4b312442b8.jpg","View":"https://hianime.to/solo-leveling-season-2-arise-from-the-shadow-19413","Name":"Solo Leveling Season 2: Arise from the Shadow","Genre":"Action, Adventure, Fantasy, Magic, Supernatural","Status":"Ongoing","Episode":"1","description":"Sung Jinwoo, the world's weakest hunter, has been given a second chance at life. He is now a powerful hunter with the ability to level up and become stronger. He must navigate a world filled with dangerous monsters and powerful hunters as he seeks to uncover the truth behind his new powers."},


    {"Id":"18","Image":"https://cdn.noitatnemucod.net/thumbnail/300x400/100/8bbe3d0785392e3ca5b179e0d281e434.jpg","View":"https://hianime.to/demon-lord-2099-19339","Name":"Demon Lord, Retry!","Genre":"Action, Adventure, Fantasy","Status":"Ongoing","Episode":"1","description":" none"},


    {"Id":"19","Image":"https://cdn.noitatnemucod.net/thumbnail/300x400/100/d2b84a8324def797365301e5ccf08166.jpg","View":"https://hianime.to/watch/the-prince-of-tennis-ii-1349?ep=19451","Name":"The Prince of Tennis II","Genre":"Action, Comedy, School, Shounen, Sports","Status":"Ongoing","Episode":"1","description":"Ryoma Echizen, a talented tennis player, joins the Seishun Academy tennis team. He faces various challenges and rivals as he strives to become the best tennis player in Japan. The series follows his growth and the team's journey to victory."},

    {"Id":"20","Image":"https://cdn.noitatnemucod.net/thumbnail/300x400/100/f6d9cbc5cc655c5600f296acb1138975.jpg","View":"https://hianime.to/watch/fire-force-979?ep=16169","Name":"Fire Force","Genre":"Action, Supernatural","Status":"Ongoing","Episode":"1","description":"In a world where spontaneous human combustion turns people into fire-wielding monsters, a group of firefighters known as the Special Fire Force is formed to combat this phenomenon. The series follows Shinra Kusakabe, a new recruit with the ability to ignite his feet, as he joins the fight against the Infernals."},

    {"Id":"21","Image":"https://cdn.noitatnemucod.net/thumbnail/300x400/100/d2dc5680b4a60875d85131124de96b78.jpg","View":"https://hianime.to/watch/rising-in-the-fire-19515?ep=133350","Name":"Rising in the Fire","Genre":"Action, Adventure, Fantasy, Magic, Supernatural","Status":"Ongoing","Episode":"1","description":"In a world where magic and technology coexist, a young hero embarks on a journey to uncover the truth behind his family's legacy. He faces powerful enemies and uncovers dark secrets as he strives to protect his loved ones."},     

    {"Id":"22","Image":"https://cdn.noitatnemucod.net/thumbnail/300x400/100/99607db327aff8feb93e702ab255e566.jpg","View":"https://hianime.to/watch/silent-house-19521","Name":"Silent House","Genre":"Action, Adventure, Fantasy, Magic, Supernatural","Status":"Ongoing","Episode":"1","description":"In a world where silence is a weapon, a group of warriors known as the Silent House must protect their city from evil forces. They use their unique abilities and advanced technology to battle against powerful enemies."},

    {"Id":"23","Image":"https://cdn.noitatnemucod.net/thumbnail/300x400/100/23cc8e120b74d5fc55050b0e88f00758.jpg","View":"https://hianime.to/watch/swallowed-star-2nd-season-18018?w=latest&ep=133270","Name":"Swallowed Star 2nd Season","Genre":"Action, Adventure, Fantasy, Magic, Supernatural","Status":"Ongoing","Episode":"1","description":"In a world where humans and monsters coexist, a young hero embarks on a journey to uncover the truth behind his family's legacy. He faces powerful enemies and uncovers dark secrets as he strives to protect his loved ones."},

    {"Id":"24","Image":"https://staticg.sportskeeda.com/editor/2023/01/9775a-16733338848947-1920.jpg","View":"https://hianime.to/watch/tokyo-revengers-christmas-showdown-18244?ep=97034","Name":"Tokyo Revengers: Christmas Showdown","Genre":"Action, Drama, Romance, Shounen","Status":"Ongoing","Episode":"1","description":"Takemichi Hanagaki discovers that he can travel back in time to save his girlfriend from a tragic fate. He must navigate the dangerous world of gang conflicts and make difficult choices to change the future."},

    {"Id":"25","Image":"https://th.bing.com/th/id/OIP.A8PLHsjNOCYCJnc9kPu5VgHaKs?rs=1&pid=ImgDetMain","View":"https://hianime.to/watch/naruto-shippuden-355?ep=7882","Name":"Naruto shippuden","Genre":"Action, Adventure, Comedy, Drama, Fantasy, Martial Arts, Shounen","Status":"Ongoing","Episode":"1","description":"Naruto Uzumaki, a young ninja with dreams of becoming the strongest Hokage, faces various challenges and enemies as he grows stronger. The series follows his journey to protect his village and uncover the truth about his past."},

    {"Id":"26","Image":"https://th.bing.com/th/id/OIP.IBGDL1RPJt9nD9fgWj5ZzgHaNK?rs=1&pid=ImgDetMain","View":"https://hianime.to/watch/lookism-18234?ep=96008","Name":"Lookism","Genre":"Action, Drama, School, Shounen","Status":"Ongoing","Episode":"1","description":"Park Hyung Suk is a high school student who is bullied for his looks. One day, he wakes up in a new body that is handsome and athletic. He must navigate the challenges of his new life while dealing with the consequences of his past."},

    {"Id":"27","Image":"https://th.bing.com/th/id/OIP.sZLz2rj6NvmcVzpUcyWClAHaKh?rs=1&pid=ImgDetMain","View":"https://9anime.org.lv/attack-on-titan-season-2-dub-episode-1/","Name":"Attack on titan season 2","Genre":"Action, Drama, Fantasy, Horror, Mystery, Shounen","Status":"Ongoing","Episode":"1","description":"In a world where humanity is on the brink of extinction due to giant humanoid creatures known as Titans, Eren Yeager and his friends join the military to fight back. They uncover dark secrets about the Titans and their own pasts."},

    {"Id":"28","Image":"https://wallpapers.com/images/featured/attack-on-titan-season-3-tui0swg3si22w20i.jpg","View":"https://9anime.org.lv/attack-on-titan-season-3-dub-episode-1/","Name":"Attack on titan season 3","Genre":"Action, Drama, Fantasy, Horror, Mystery, Shounen","Status":"Ongoing","Episode":"1","description":"In the third season of Attack on Titan, Eren Yeager and his friends continue their fight against the Titans while uncovering the truth about their world. They face new challenges and powerful enemies as they strive to protect humanity."},

    {"Id":"29","Image":"https://tse2.mm.bing.net/th?id=OIP.HiIPh7ddRzdJDEzjg8JFvwHaEK&rs=1&pid=ImgDetMain","View":"https://hianime.to/watch/black-clover-2404?ep=27377","Name":"Black Clover","Genre":"Action, Adventure, Comedy, Fantasy, Magic, Shounen","Status":"Ongoing","Episode":"1","description":"Asta and Yuno are orphans who dream of becoming the Wizard King. Asta is determined to prove that hard work can overcome any obstacle, while Yuno possesses incredible magical talent. Together, they face powerful enemies and strive to achieve their dreams."},
 
    {"Id":"30","Image":"https://www.anime-planet.com/images/manga/covers/berserk-14.jpg?t=1547479613","View":"https://hianime.to/watch/berserk-2016-5978","Name":"Berserk","Genre":"Action, Adventure, Drama, Fantasy, Horror, Supernatural","Status":"Ongoing","Episode":"1","description":"Guts, a lone mercenary with a tragic past, wields a massive sword and battles against demonic forces. He seeks revenge against his former friend Griffith, who betrayed him and sacrificed their comrades to become a powerful demon."},
]

module.exports = {animes2};
