
const animes2 = [
    {"Id":"17","Image":"https://cdn.noitatnemucod.net/thumbnail/300x400/100/65f92e6e315a931ef872da4b312442b8.jpg","View":"https://hianime.to/solo-leveling-season-2-arise-from-the-shadow-19413","Name":"Solo Leveling Season 2: Arise from the Shadow","Genre":"Action, Adventure, Fantasy, Magic, Supernatural","Status":"Ongoing","Episode":"1","description":"Sung Jinwoo, the world's weakest hunter, has been given a second chance at life. He is now a powerful hunter with the ability to level up and become stronger. He must navigate a world filled with dangerous monsters and powerful hunters as he seeks to uncover the truth behind his new powers."},

    {"Id":"18","Image":"https://cdn.noitatnemucod.net/thumbnail/300x400/100/3b185ed9d10aa300bb0cb7fc35b84999.jpg","View":"https://hianime.to/case-closed-323","Name":"Case Closed","Genre":"Adventure, Comedy, Mystery, Police, Shounen","Status":"Ongoing","Episode":"1","description":"Shinichi Kudo, a high school detective, is poisoned and transformed into a child. He takes on the alias Conan Edogawa and continues to solve cases while searching for a way to return to his original form. Along the way, he encounters various criminals and mysteries."},

    {"Id":"19","Image":"https://cdn.noitatnemucod.net/thumbnail/300x400/100/8bbe3d0785392e3ca5b179e0d281e434.jpg","View":"https://hianime.to/demon-lord-2099-19339","Name":"Demon Lord, Retry!","Genre":"Action, Adventure, Fantasy","Status":"Ongoing","Episode":"1","description":" none"},

    {"Id":"20","Image":"https://cdn.noitatnemucod.net/thumbnail/300x400/100/170a925f89b941a98f0be20ad3ea6e4a.jpg","View":"https://hianime.to/watch/lupin-iii-1126?ep=17477","Name":"Lupin III","Genre":"Action, Adventure, Comedy, Mystery, Seinen","Status":"Ongoing","Episode":"1","description":"Lupin III is a master thief and the grandson of Arsène Lupin. He travels the world with his gang, stealing valuable treasures while evading capture by the police and rival thieves. The series follows their heists and adventures."},

    {"Id":"21","Image":"https://cdn.noitatnemucod.net/thumbnail/300x400/100/4aed479d47c67d6883719b2c7b32f86d.jpg","View":"https://hianime.to/watch/radiant-season-2-1142?ep=17662","Name":"Radiant Season 2","Genre":"Action, Adventure, Fantasy, Magic, Shounen","Status":"Ongoing","Episode":"1","description":"Seth, a young sorcerer, continues his quest to find the Radiant, a mythical place where the Nemesis monsters are said to originate. He faces new challenges and enemies while trying to protect his friends and uncover the truth about the Radiant."},

    {"Id":"22","Image":"https://cdn.noitatnemucod.net/thumbnail/300x400/100/5d43dde976d0c68a5ed392c077874d95.jpg","View":"https://hianime.to/watch/voltage-fighter-gowcaizer-ova-17896?ep=83080","Name":"Voltage Fighter Gowcaizer OVA","Genre":"Action, Adventure, Martial Arts, Sci-Fi, Super Power","Status":"Ongoing","Episode":"1","description":"In a world where martial arts and technology collide, a group of fighters known as the Voltage Fighters must protect their city from evil forces. They use their unique abilities and advanced technology to battle against powerful enemies."},

    {"Id":"23","Image":"https://cdn.noitatnemucod.net/thumbnail/300x400/100/d2b84a8324def797365301e5ccf08166.jpg","View":"https://hianime.to/watch/the-prince-of-tennis-ii-1349?ep=19451","Name":"The Prince of Tennis II","Genre":"Action, Comedy, School, Shounen, Sports","Status":"Ongoing","Episode":"1","description":"Ryoma Echizen, a talented tennis player, joins the Seishun Academy tennis team. He faces various challenges and rivals as he strives to become the best tennis player in Japan. The series follows his growth and the team's journey to victory."},

    {"Id":"24","Image":"https://cdn.noitatnemucod.net/thumbnail/300x400/100/e94982ae55f3f51d2821df63fc9c577d.jpg","View":"https://hianime.to/watch/youre-my-love-prize-16245?ep=50400","Name":"You're My Love Prize in Viewfinder","Genre":"Action, Drama, Romance, Yaoi","Status":"Ongoing","Episode":"1","description":"The story follows the relationship between a photographer and a model as they navigate the challenges of their careers and personal lives. Their bond deepens as they face various obstacles together."},

    {"Id":"25","Image":"https://cdn.noitatnemucod.net/thumbnail/300x400/100/f6d9cbc5cc655c5600f296acb1138975.jpg","View":"https://hianime.to/watch/fire-force-979?ep=16169","Name":"Fire Force","Genre":"Action, Supernatural","Status":"Ongoing","Episode":"1","description":"In a world where spontaneous human combustion turns people into fire-wielding monsters, a group of firefighters known as the Special Fire Force is formed to combat this phenomenon. The series follows Shinra Kusakabe, a new recruit with the ability to ignite his feet, as he joins the fight against the Infernals."},

    {"Id":"26","Image":"https://cdn.noitatnemucod.net/thumbnail/300x400/100/d2dc5680b4a60875d85131124de96b78.jpg","View":"https://hianime.to/watch/rising-in-the-fire-19515?ep=133350","Name":"Rising in the Fire","Genre":"Action, Adventure, Fantasy, Magic, Supernatural","Status":"Ongoing","Episode":"1","description":"In a world where magic and technology coexist, a young hero embarks on a journey to uncover the truth behind his family's legacy. He faces powerful enemies and uncovers dark secrets as he strives to protect his loved ones."},     

    {"Id":"27","Image":"https://cdn.noitatnemucod.net/thumbnail/300x400/100/99607db327aff8feb93e702ab255e566.jpg","View":"https://hianime.to/watch/silent-house-19521","Name":"Silent House","Genre":"Action, Adventure, Fantasy, Magic, Supernatural","Status":"Ongoing","Episode":"1","description":"In a world where silence is a weapon, a group of warriors known as the Silent House must protect their city from evil forces. They use their unique abilities and advanced technology to battle against powerful enemies."},

    {"Id":"28","Image":"https://cdn.noitatnemucod.net/thumbnail/300x400/100/23cc8e120b74d5fc55050b0e88f00758.jpg","View":"https://hianime.to/watch/swallowed-star-2nd-season-18018?w=latest&ep=133270","Name":"Swallowed Star 2nd Season","Genre":"Action, Adventure, Fantasy, Magic, Supernatural","Status":"Ongoing","Episode":"1","description":"In a world where humans and monsters coexist, a young hero embarks on a journey to uncover the truth behind his family's legacy. He faces powerful enemies and uncovers dark secrets as he strives to protect his loved ones."},

    {"Id":"29","Image":"https://cdn.noitatnemucod.net/thumbnail/300x400/100/5dc640871a61596483b630918f8c2e04.jpg","View":"https://hianime.to/watch/loner-life-in-another-world-19337?ep=128280","Name":"Loner Life in Another World","Genre":"Action, Adventure, Fantasy, Magic, Supernatural","Status":"Ongoing","Episode":"1","description":"In a world where magic and technology coexist, a young hero embarks on a journey to uncover the truth behind his family's legacy. He faces powerful enemies and uncovers dark secrets as he strives to protect his loved ones."},

]

module.exports = {animes2};
